// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgyI7heXFrH-xfdOi7F1sDDmHcCl2we0',
    appId: '1:58745854775:web:8e41763814783bbe5a98b2',
    messagingSenderId: '58745854775',
    projectId: 'minimal-messenger',
    authDomain: 'minimal-messenger.firebaseapp.com',
    storageBucket: 'minimal-messenger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcca3yGXuelLXO1vl3-ceoipJsBXn6tPU',
    appId: '1:58745854775:android:e95a9806a8c9b21b5a98b2',
    messagingSenderId: '58745854775',
    projectId: 'minimal-messenger',
    storageBucket: 'minimal-messenger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrKAiBzvIcFW-qrl9oXbGfyN0dh5a7-S0',
    appId: '1:58745854775:ios:93851423f0f4af4e5a98b2',
    messagingSenderId: '58745854775',
    projectId: 'minimal-messenger',
    storageBucket: 'minimal-messenger.appspot.com',
    iosBundleId: 'com.example.minimalMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrKAiBzvIcFW-qrl9oXbGfyN0dh5a7-S0',
    appId: '1:58745854775:ios:1551ece875f25ad25a98b2',
    messagingSenderId: '58745854775',
    projectId: 'minimal-messenger',
    storageBucket: 'minimal-messenger.appspot.com',
    iosBundleId: 'com.example.minimalMessenger.RunnerTests',
  );
}
